# **LIST**

In [ ]:
from datetime import date

# Data Mahasiswa
Mahasiswa = [
    {
        "nama": "Khairun Nisa Al Hakim",
        "NIM": "2024071001",
        "prodi": "Informatika",
        "mata_kuliah": "Pengantar Kecerdasan Buatan",
        "tanggal": date.today().strftime("%d-%m-%Y"),
        "universitas": "Universitas Pembangunan Jaya"
    }
]

# Menampilkan data
for mhs in Mahasiswa:
    print("Nama        :", mhs["nama"])
    print("NIM         :", mhs["NIM"])
    print("Prodi       :", mhs["prodi"])
    print("Mata Kuliah :", mhs["mata_kuliah"])
    print("Tanggal     :", mhs["tanggal"])
    print("Universitas :", mhs["universitas"])

Nama        : Khairun Nisa Al Hakim
NIM         : 2024071001
Prodi       : Informatika
Mata Kuliah : Pengantar Kecerdasan Buatan
Tanggal     : 15-09-2025
Universitas : Universitas Pembangunan Jaya


In [ ]:
from datetime import date
tgl_v1 = date.today()

import datetime as vDate
hari = vDate.date.day

tanggal = vDate.date.today()
print(hari)
print(tanggal)

Mahasiswa = [
    "Khairun Nisa Al Hakim", "2024071001", "Informatika", "DAA", f"{tanggal}", "Universitas Pembangunan Jaya"
    ]

print(Mahasiswa)

<attribute 'day' of 'datetime.date' objects>
2025-09-15
['Khairun Nisa Al Hakim', '2024071001', 'Informatika', 'DAA', '2025-09-15', 'Universitas Pembangunan Jaya']


In [ ]:
print("NIM", mahasiswa[1:2])

NIM ['2024071001']


In [ ]:
print("Prodi", mahasiswa[2:3])

Prodi ['Informatika']


In [ ]:
print("NIM & Prodi", mahasiswa[1:3])

NIM & Prodi ['2024071001', 'Informatika']


In [ ]:
print("Mata Kuliah Tanggal Berapa?", mahasiswa[3:5])

Mata Kuliah Tanggal Berapa? ['DAA', '15-9-2025']


In [ ]:
bin_colors = ['Red', 'Green', 'Blue', 'Yellow']
for aColor in bin_colors:
  print(aColor)
  print(aColor + ' square')

Red
Red square
Green
Green square
Blue
Blue square
Yellow
Yellow square


# **NESTED TUPLE**

In [ ]:
for aMhs in mahasiswa:
  print(aMhs + ' UPJ')

Kai UPJ
2024071001 UPJ
Informatika UPJ
DAA UPJ
15-9-2025 UPJ
Universitas Pembangunan Jaya UPJ


In [ ]:
nested = (100,(200,400,600),300,(400,800))
print(nested)

(100, (200, 400, 600), 300, (400, 800))


# **KEY**

In [ ]:
bin_colors = ['Red', 'Green', 'Blue', 'Yellow']
bin_colors[1]

'Green'

In [ ]:
upj = ("Universitas", "Pembangunan", "Jaya")
print(upj)

('Universitas', 'Pembangunan', 'Jaya')


In [ ]:
bin_colors  = {
  "manual_color": "Yellow",
  "approved_color": "Green",
  "refused_color": "Red"
}
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [ ]:
bin_colors.get('approved_color')

'Green'

In [ ]:
bin_colors['approved_color']

'Green'

In [ ]:
bin_colors['approved_color']="Purple"
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Purple', 'refused_color': 'Red'}


# **KEY AND VALUE**

In [ ]:
mahasiswa = {
    "Nama": "Kai",
    "NIM": "2024071001",
    "Prodi": "Informatika",
    "Universitas": "UPJ"
}

print(mahasiswa)

{'Nama': 'Kai', 'NIM': '2024071001', 'Prodi': 'Informatika', 'Universitas': 'UPJ'}


In [ ]:
mahasiswa.get('Nama')

'Kai'

In [ ]:
mahasiswa['NIM']

'2024071001'

In [ ]:
mahasiswa['Prodi']

'Informatika'

In [ ]:
mahasiswa['Universitas']

'UPJ'

# **SET**

In [ ]:
green = {'grass', 'leaves'}
print(green)

{'grass', 'leaves'}


In [ ]:
green = {'grass', 'leaves', 'leaves'}
print(green)

{'grass', 'leaves'}


# **GABUNGAN DAN IRISAN DATA**

In [ ]:
yellow = {'dandelions', 'fire hydrant', 'leaves'}
red = {'fire hydrant', 'blood', 'rose', 'leaves'}

print (yellow|red)

{'rose', 'dandelions', 'blood', 'fire hydrant', 'leaves'}


In [ ]:
print (yellow&red)

{'fire hydrant', 'leaves'}


# **DATAFRAME**

In [ ]:
import pandas as pd
df = pd.DataFrame([
    ['1', 'Fares', 32, True],
    ['2', 'Elena', 23, False],
    ['3', 'Steven', 40, True]])
df

0       1   2      3
0  1   Fares  32   True
1  2   Elena  23  False
2  3  Steven  40   True

Memberi Judul Kolom

In [ ]:
df.columns = ['id', 'name', 'age', 'decision']
df

id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True

Memfilter Data

In [ ]:
df[['name','age']]

name  age
0   Fares   32
1   Elena   23
2  Steven   40

In [ ]:
df.iloc[:,3]

0     True
1    False
2     True
Name: decision, dtype: bool

Memfilter Data Bagian Row

In [ ]:
df.iloc[1:3,:]

id    name  age  decision
1  2   Elena   23     False
2  3  Steven   40      True

Memfilter Data di Atas Umur 30

In [ ]:
df[df.age>30]

id    name  age  decision
0  1   Fares   32      True
2  3  Steven   40      True

In [ ]:
Memfilter Data yang Memenuhi Kiri dan Kanan

In [ ]:
df[(df.age<35)&(df.decision==True)]

id   name  age  decision
0  1  Fares   32      True

Latihan Memfilter Data

In [ ]:
import pandas as pd
df = pd.DataFrame([
    ['1', 'Informatika', 50, 30, 20],
    ['2', 'Sistem Informasi', 55, 30, 25],
    ['3', 'Teknik Sipil', 40, 30, 10]])
df

0                 1   2   3   4
0  1       Informatika  50  30  20
1  2  Sistem Informasi  55  30  25
2  3      Teknik Sipil  40  30  10

In [ ]:
df.columns = ['No', 'Prodi', 'Mahasiswa', 'LakiLaki', 'Perempuan']
df

No             Prodi  Mahasiswa  LakiLaki  Perempuan
0  1       Informatika         50        30         20
1  2  Sistem Informasi         55        30         25
2  3      Teknik Sipil         40        30         10

In [ ]:
df[['Prodi','Mahasiswa']]

Prodi  Mahasiswa
0       Informatika         50
1  Sistem Informasi         55
2      Teknik Sipil         40

# **MATRIKS**

In [ ]:
import numpy as np
myMatrix = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print(myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [ ]:
print(type(myMatrix))

<class 'numpy.ndarray'>


Latihan Matriks

In [ ]:
import numpy as np
myMatrix = np.array([[100, 200, 300], [700, 600, 500], [900, 1000, 800]])
print(myMatrix)

[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]


Transpos Matrix

In [ ]:
import numpy as np
myMatrix = np.array([[100, 700, 900], [200, 600, 1000], [300, 500, 800]])
print(myMatrix)

[[ 100  700  900]
 [ 200  600 1000]
 [ 300  500  800]]


# **VECTOR**

In [ ]:
myVector = [22, 23, 44, 55]
print(myVector)

[22, 23, 44, 55]


In [ ]:
print(type(myVector))

<class 'list'>


In [ ]:
myVector = np.array([22,33,44,55])
print(myVector)

[22 33 44 55]


In [ ]:
print(type(myVector))

<class 'numpy.ndarray'>


# **STACK**

In [ ]:
class Stack:
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def push(self, item):
        self.items.append(item)
    def pop(self):
        return self.items.pop()
    def peek(self):
        return self.items[len(self.items)-1]
    def size(self):
        return len(self.items)

In [86]:
stack = Stack()
stack.push("Red")
stack.push("Green")
stack.push("Blue")
stack.push("Yellow")

In [87]:
print(stack.pop())

Yellow


In [88]:
print(stack.isEmpty())

False


In [89]:
print(stack.peek())

Blue


In [90]:
print(stack.size())

3


# *QUEUE*

In [91]:
class Queue(object):
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def enqueue(self, item):
        self.items.insert(0, item)
    def dequeue(self):
        return self.items.pop()
    def size(self):
        return len(self.items)

In [94]:
queue = Queue()

In [95]:
queue.enqueue("Red")
queue.enqueue("Green")
queue.enqueue("Blue")
queue.enqueue("Yellow")

In [96]:
print(queue.size())

4
